{
 "title": "Ability Camera",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "CPU Percent Average",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(cpu_percent{quantile=\"0.500000\"})by(node_ip, service_capability, job)",
     "legendFormat": "AVG(0.5) - {{job}}, {{service_capability}}, NodeIP={{node_ip}}"
    }
   ]
  },
  {
   "title": "RAM Percent Average",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 5, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(ram_percent{quantile=\"0.500000\"})by(node_ip, service_capability, job)",
     "legendFormat": "AVG(0.5) - {{job}}, {{service_capability}}, NodeIP={{node_ip}}"
    }
   ]
  },
  {
   "title": "Number of Event",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 10, "y": 0 },
   "targets": [
    {
     "expr": "packet_event_number",
     "legendFormat": "{{job}}, {{service_capability}}, NodeIP={{node_ip}}"
    }
   ]
  },
  {
   "title": "Number of Event",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 0 },
   "targets": [
    {
     "expr": "packet_event_number",
     "legendFormat": "{{job}}, {{service_capability}}, NodeIP={{node_ip}}"
    }
   ]
  },
  {
   "title": "Number of WS Log gw Connection",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "ws_log_gw_connection_number",
     "legendFormat": "{{job}}, {{service_capability}}, NodeIP={{node_ip}}"
    }
   ]
  },
  {
   "title": "Number of WS Event Connection",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 5, "x": 5, "y": 9 },
   "targets": [
    {
     "expr": "ws_event_connection_number",
     "legendFormat": "{{job}}, {{service_capability}}, NodeIP={{node_ip}}"
    }
   ]
  },
  {
   "title": "Pipeline Latency Average",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 10, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(cam_pipeline_latency{quantile=\"0.500000\"})by(node_ip, service_capability, job)",
     "legendFormat": "AVG(0.5) - {{job}}, {{service_capability}}, NodeIP={{node_ip}}"
    }
   ]
  },
  {
   "title": "Size of Log gw",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "packet_log_gw_size",
     "legendFormat": "{{job}}, {{service_capability}}, NodeIP={{node_ip}}"
    }
   ]
  },
  {
   "title": "Size of Event",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "packet_event_size",
     "legendFormat": "{{job}}, {{service_capability}}, NodeIP={{node_ip}}"
    }
   ]
  }
 ]
}