global:
  scrape_interval:     15s
  evaluation_interval: 15s

  external_labels:
      monitor: 'docker-host-alpha'
      
scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'visionaire4'
    proxy_url: http://localhost:80/
    static_configs:
      - targets: ['localhost:9100','localhost:4004','localhost:9853', 'localhost:8081']



