{
 "title": "Nginx Log Metrics",
 "description": "NGINX Log metrics with Prometheus based on https://www.martin-helmich.de/en/blog/monitoring-nginx.html. Based on namespace prefix 'nginx'. If different, you may need to adjust the metrics.",
 "tags": [
  "nginx",
  "http"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Average Response Time",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 14, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(cluster_one_http_response_time_seconds_sum[5m])) by (instance) / sum(rate(cluster_one_http_response_time_seconds_count[5m])) by (instance)"
    }
   ]
  },
  {
   "title": "Requests per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(cluster_one_http_response_time_seconds_count[1m])) by (instance)"
    }
   ]
  },
  {
   "title": "Requests per Second by Status Code",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(cluster_one_http_response_count_total[1m])) by (status)",
     "legendFormat": "Status Code: {{status}}"
    }
   ]
  },
  {
   "title": "Response time (90% quantile)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 14, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "cluster_one_http_response_time_seconds{quantile=\"0.9\",method=\"POST\",status=~\"2[0-9]*\"}"
    }
   ]
  },
  {
   "title": "Unparsed Log",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 14, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "cluster_one_parse_errors_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "HTTP Traffic (In Bytes)",
   "type": "timeseries",
   "description": "Response sizes in bytes",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(cluster_one_http_response_size_bytes[5m])) by (instance)"
    }
   ]
  }
 ]
}