{
 "title": "v4 & fremisN centralized monitoring",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "job", "label": "host ", "query": "server LB" },
   { "name": "err_range", "label": "Error Rate Range", "query": "1m,2m,5m,10m,30m,1h,6h,12h,1d" },
   {
    "name": "container",
    "label": "Container",
    "query": {
     "query": "label_values({__name__=~\"container.*\", job=\"$job\"},name)"
    }
   },
   {
    "name": "gpu",
    "label": "GPU",
    "query": {
     "query": "label_values(nvidia_smi_index{job=\"$job\"}, uuid)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU/Mem/Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "CPU Busy",
     "type": "gauge",
     "description": "Busy state of all CPU cores together",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(((count(count(node_cpu_seconds_total{job=\"$job\"}) by (cpu))) - avg(sum by (mode)(rate(node_cpu_seconds_total{mode='idle',job=\"$job\"}[$__rate_interval])))) * 100) / count(count(node_cpu_seconds_total{job=\"$job\"}) by (cpu))"
      }
     ]
    },
    {
     "title": "Sys Load (15m avg)",
     "type": "gauge",
     "description": "Busy state of all CPU cores together (15 min average)",
     "gridPos": { "h": 4, "w": 3, "x": 3, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg without (mode,cpu) (\n  1 - rate(node_cpu_seconds_total{mode=\"idle\",job=\"$job\"}[1m])\n) * 100"
      }
     ]
    },
    {
     "title": "RAM Used",
     "type": "gauge",
     "description": "Non available RAM memory",
     "gridPos": { "h": 4, "w": 3, "x": 6, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100 - ((node_memory_MemAvailable_bytes{job=\"$job\"} * 100) / node_memory_MemTotal_bytes{job=\"$job\"})"
      }
     ]
    },
    {
     "title": "SWAP Used",
     "type": "gauge",
     "description": "Used Swap",
     "gridPos": { "h": 4, "w": 3, "x": 9, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "((node_memory_SwapTotal_bytes{job=\"$job\"} - node_memory_SwapFree_bytes{job=\"$job\"}) / (node_memory_SwapTotal_bytes{job=\"$job\"} )) * 100"
      }
     ]
    },
    {
     "title": "Root FS Used",
     "type": "gauge",
     "description": "Root FS Used",
     "gridPos": { "h": 4, "w": 3, "x": 12, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100 - ((node_filesystem_avail_bytes{job=\"$job\",mountpoint=\"/\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{job=\"$job\",mountpoint=\"/\",fstype!=\"rootfs\"})"
      }
     ]
    },
    {
     "title": "/data patition Used",
     "type": "gauge",
     "description": "/data partition Used",
     "gridPos": { "h": 4, "w": 3, "x": 15, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100 - ((node_filesystem_avail_bytes{job=\"$job\",mountpoint=\"/data\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{job=\"$job\",mountpoint=\"/data\",fstype!=\"rootfs\"})"
      }
     ]
    },
    {
     "title": "CPU Cores",
     "type": "stat",
     "description": "Total number of CPU cores",
     "gridPos": { "h": 2, "w": 2, "x": 18, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(count(node_cpu_seconds_total{job=\"$job\"}) by (cpu))"
      }
     ]
    },
    {
     "title": "RAM Total",
     "type": "stat",
     "description": "Total RAM",
     "gridPos": { "h": 2, "w": 2, "x": 20, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "node_memory_MemTotal_bytes{job=\"$job\"}"
      }
     ]
    },
    {
     "title": "SWAP Total",
     "type": "stat",
     "description": "Total SWAP",
     "gridPos": { "h": 2, "w": 2, "x": 22, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "node_memory_SwapTotal_bytes{job=\"$job\"}"
      }
     ]
    },
    {
     "title": "RootFS Total",
     "type": "stat",
     "description": "Total RootFS",
     "gridPos": { "h": 2, "w": 2, "x": 18, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "node_filesystem_size_bytes{job=\"$job\",mountpoint=\"/\",fstype!=\"rootfs\"}"
      }
     ]
    },
    {
     "title": "/data Total",
     "type": "stat",
     "description": "/datav Total",
     "gridPos": { "h": 2, "w": 2, "x": 20, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "node_filesystem_size_bytes{job=\"$job\",mountpoint=\"/data\",fstype!=\"rootfs\"}"
      }
     ]
    },
    {
     "title": "Uptime",
     "type": "stat",
     "description": "System uptime",
     "gridPos": { "h": 2, "w": 2, "x": 22, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "node_time_seconds{job=\"$job\"} - node_boot_time_seconds{job=\"$job\"}"
      }
     ]
    },
    {
     "title": "CPU Basic",
     "type": "graph",
     "description": "Basic CPU info",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 61 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode=\"system\",job=\"$job\"}[$__rate_interval])) * 100",
       "legendFormat": "Busy System"
      },
      {
       "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode='user',job=\"$job\"}[$__rate_interval])) * 100",
       "legendFormat": "Busy User"
      },
      {
       "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode='iowait',job=\"$job\"}[$__rate_interval])) * 100",
       "legendFormat": "Busy Iowait"
      },
      {
       "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode=~\".*irq\",job=\"$job\"}[$__rate_interval])) * 100",
       "legendFormat": "Busy IRQs"
      },
      {
       "expr": "sum (rate(node_cpu_seconds_total{mode!='idle',mode!='user',mode!='system',mode!='iowait',mode!='irq',mode!='softirq',job=\"$job\"}[$__rate_interval])) * 100",
       "legendFormat": "Busy Other"
      },
      {
       "expr": "sum by (mode)(rate(node_cpu_seconds_total{mode='idle',job=\"$job\"}[$__rate_interval])) * 100",
       "legendFormat": "Idle"
      }
     ]
    },
    {
     "title": "Memory Basic",
     "type": "graph",
     "description": "Basic memory usage",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 61 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "node_memory_MemTotal_bytes{job=\"$job\"}",
       "legendFormat": "RAM Total"
      },
      {
       "expr": "node_memory_MemTotal_bytes{job=\"$job\"} - node_memory_MemFree_bytes{job=\"$job\"} - (node_memory_Cached_bytes{job=\"$job\"} + node_memory_Buffers_bytes{job=\"$job\"})",
       "legendFormat": "RAM Used"
      },
      {
       "expr": "node_memory_Cached_bytes{job=\"$job\"} + node_memory_Buffers_bytes{job=\"$job\"}",
       "legendFormat": "RAM Cache + Buffer"
      },
      {
       "expr": "node_memory_MemFree_bytes{job=\"$job\"}",
       "legendFormat": "RAM Free"
      },
      {
       "expr": "(node_memory_SwapTotal_bytes{job=\"$job\"} - node_memory_SwapFree_bytes{job=\"$job\"})",
       "legendFormat": "SWAP Used"
      }
     ]
    },
    {
     "title": "Network Traffic Basic",
     "type": "graph",
     "description": "Basic network info per interface",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 67 },
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "expr": "rate(node_network_receive_bytes_total{job=\"$job\"}[$__rate_interval])*8",
       "legendFormat": "recv {{device}}"
      },
      {
       "expr": "rate(node_network_transmit_bytes_total{job=\"$job\"}[$__rate_interval])*8",
       "legendFormat": "trans {{device}} "
      }
     ]
    },
    {
     "title": "Disk Space Used Basic",
     "type": "graph",
     "description": "Disk space used of all filesystems mounted",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 67 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "100 - ((node_filesystem_avail_bytes{job=\"$job\",device!~'rootfs'} * 100) / node_filesystem_size_bytes{job=\"$job\",device!~'rootfs'})",
       "legendFormat": "{{mountpoint}}"
      }
     ]
    }
   ]
  },
  {
   "title": "GPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Name",
     "type": "stat",
     "description": "The official product name of the GPU. This is an alphanumeric string. For all products.",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "nvidia_smi_gpu_info{job=\"$job\", uuid=\"$gpu\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "P-State",
     "type": "stat",
     "description": "The current performance state for the GPU. States range from P0 (maximum performance) to P12 (minimum performance).",
     "gridPos": { "h": 3, "w": 2, "x": 4, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "prefix:P" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "nvidia_smi_pstate{job=\"$job\", uuid=\"$gpu\"}"
      }
     ]
    },
    {
     "title": "GPU Utilization %",
     "type": "gauge",
     "description": "Percent of time over the past sample period during which one or more kernels was executing on the GPU.\nThe sample period may be between 1 second and 1/6 second depending on the product.",
     "gridPos": { "h": 5, "w": 3, "x": 6, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "nvidia_smi_utilization_gpu_ratio{ job=\"$job\", uuid=\"$gpu\"}",
       "legendFormat": "{{uuid}}"
      }
     ]
    },
    {
     "title": "Power Draw %",
     "type": "gauge",
     "description": "The last measured power draw for the entire board, in watts. Only available if power management is supported. This reading is accurate to within +/- 5 watts / The software power limit in watts.",
     "gridPos": { "h": 5, "w": 3, "x": 9, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "nvidia_smi_power_draw_watts{job=\"$job\", uuid=\"$gpu\"} / nvidia_smi_power_default_limit_watts{job=\"$job\", uuid=\"$gpu\"}"
      }
     ]
    },
    {
     "title": "Fan Speed %",
     "type": "gauge",
     "description": "The fan speed value is the percent of the product's maximum noise tolerance fan speed that the device's fan is currently intended to run at. This value may exceed 100% in certain cases. Note: The reported speed is the intended fan speed. If the fan is physically blocked and unable to spin, this output will not match the actual fan speed. Many parts do not report fan speeds because they rely on cooling via fans in the surrounding enclosure.\n",
     "gridPos": { "h": 5, "w": 3, "x": 12, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "nvidia_smi_fan_speed_ratio{job=\"$job\", uuid=\"$gpu\"}"
      }
     ]
    },
    {
     "title": "Temperature",
     "type": "gauge",
     "description": "Core GPU temperature. in degrees C.",
     "gridPos": { "h": 5, "w": 3, "x": 15, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "nvidia_smi_temperature_gpu{job=\"$job\", uuid=\"$gpu\"}",
       "legendFormat": "{{uuid}}"
      }
     ]
    },
    {
     "title": "Memory Utilization %",
     "type": "graph",
     "description": "Percent of time over the past sample period during which global (device) memory was being read or written.\nThe sample period may be between 1 second and 1/6 second depending on the product.",
     "gridPos": { "h": 5, "w": 6, "x": 18, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "nvidia_smi_utilization_memory_ratio{job=\"$job\", uuid=\"$gpu\"}",
       "legendFormat": "{{uuid}}"
      }
     ]
    },
    {
     "title": "Driver Version",
     "type": "stat",
     "description": "The version of the installed NVIDIA display driver. This is an alphanumeric string.",
     "gridPos": { "h": 2, "w": 3, "x": 0, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "nvidia_smi_gpu_info{job=\"$job\", uuid=\"$gpu\"}",
       "legendFormat": "{{driver_version}}"
      }
     ]
    },
    {
     "title": "Vbios Version",
     "type": "stat",
     "description": "The BIOS of the GPU board.",
     "gridPos": { "h": 2, "w": 3, "x": 3, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "nvidia_smi_gpu_info{job=\"$job\", uuid=\"$gpu\"}",
       "legendFormat": "{{vbios_version}}"
      }
     ]
    },
    {
     "title": "Throttle Reasons",
     "type": "bargauge",
     "description": "Information about factors that are reducing the frequency of clocks. If all throttle reasons are returned as \"Not Active\" it means that clocks are running as high as possible.",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 63 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "nvidia_smi_clocks_throttle_reasons_gpu_idle{job=\"$job\", uuid=\"$gpu\"}",
       "legendFormat": "Idle"
      },
      {
       "expr": "nvidia_smi_clocks_throttle_reasons_hw_thermal_slowdown{job=\"$job\", uuid=\"$gpu\"}",
       "legendFormat": "HW Thermal Slowdown"
      },
      {
       "expr": "nvidia_smi_clocks_throttle_reasons_sw_power_cap{job=\"$job\", uuid=\"$gpu\"}",
       "legendFormat": "SW Power Cap"
      },
      {
       "expr": "nvidia_smi_clocks_throttle_reasons_applications_clocks_setting{job=\"$job\", uuid=\"$gpu\"}",
       "legendFormat": "App Clocks Setting"
      },
      {
       "expr": "nvidia_smi_clocks_throttle_reasons_hw_power_brake_slowdown{job=\"$job\", uuid=\"$gpu\"}",
       "legendFormat": "HW Power Brake"
      },
      {
       "expr": "nvidia_smi_clocks_throttle_reasons_sw_thermal_slowdown{job=\"$job\", uuid=\"$gpu\"}",
       "legendFormat": "SW Thermal Slowdown"
      },
      {
       "expr": "nvidia_smi_clocks_throttle_reasons_sync_boost{job=\"$job\", uuid=\"$gpu\"}",
       "legendFormat": "Sync Boost"
      }
     ]
    },
    {
     "title": "GPU Clock Speed %",
     "type": "gauge",
     "description": "Current frequency of graphics (shader) clock\n/\nMaximum frequency of graphics (shader) clock.\n",
     "gridPos": { "h": 5, "w": 3, "x": 6, "y": 63 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "nvidia_smi_clocks_current_graphics_clock_hz{job=\"$job\", uuid=\"$gpu\"} / nvidia_smi_clocks_max_graphics_clock_hz{job=\"$job\", uuid=\"$gpu\"}"
      }
     ]
    },
    {
     "title": "Memory Clock Speed %",
     "type": "gauge",
     "description": "Current frequency of memory clock / Maximum frequency of memory clock",
     "gridPos": { "h": 5, "w": 3, "x": 9, "y": 63 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "nvidia_smi_clocks_current_memory_clock_hz{job=\"$job\", uuid=\"$gpu\"} / nvidia_smi_clocks_max_memory_clock_hz{job=\"$job\", uuid=\"$gpu\"}"
      }
     ]
    },
    {
     "title": "Memory Allocation %",
     "type": "gauge",
     "description": "Total memory allocated by active contexts / Total installed GPU memory.",
     "gridPos": { "h": 5, "w": 3, "x": 12, "y": 63 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "nvidia_smi_memory_used_bytes{job=\"$job\", uuid=\"$gpu\"} / nvidia_smi_memory_total_bytes{job=\"$job\", uuid=\"$gpu\"}"
      }
     ]
    },
    {
     "title": "Memory Utilization %",
     "type": "gauge",
     "description": "Percent of time over the past sample period during which global (device) memory was being read or written.\nThe sample period may be between 1 second and 1/6 second depending on the product.",
     "gridPos": { "h": 5, "w": 3, "x": 15, "y": 63 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "nvidia_smi_utilization_memory_ratio{job=\"$job\", uuid=\"$gpu\"}"
      }
     ]
    },
    {
     "title": "GPU Utilization %",
     "type": "graph",
     "description": "Percent of time over the past sample period during which one or more kernels was executing on the GPU.\nThe sample period may be between 1 second and 1/6 second depending on the product.",
     "gridPos": { "h": 5, "w": 6, "x": 18, "y": 63 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "nvidia_smi_utilization_gpu_ratio{job=\"$job\", uuid=\"$gpu\"}"
      }
     ]
    },
    {
     "title": "Memory Allocation",
     "type": "graph",
     "description": "Total memory allocated by active contexts.",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "nvidia_smi_memory_used_bytes{job=\"$job\", uuid=\"$gpu\"}",
       "legendFormat": "{{uuid}}"
      }
     ]
    },
    {
     "title": "Temperature",
     "type": "graph",
     "description": "Core GPU temperature. in degrees C.",
     "gridPos": { "h": 5, "w": 6, "x": 6, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "yaxes": [
      { "format": "celsius" }
     ],
     "targets": [
      {
       "expr": "nvidia_smi_temperature_gpu{job=\"$job\", uuid=\"$gpu\"}",
       "legendFormat": "{{uuid}}"
      }
     ]
    },
    {
     "title": "Power Draw",
     "type": "graph",
     "description": "The last measured power draw for the entire board, in watts. Only available if power management is supported. This reading is accurate to within +/- 5 watts",
     "gridPos": { "h": 5, "w": 6, "x": 12, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "watt" } },
     "yaxes": [
      { "format": "watt" }
     ],
     "targets": [
      {
       "expr": "nvidia_smi_power_draw_watts{job=\"$job\", uuid=\"$gpu\"}",
       "legendFormat": "{{uuid}}"
      }
     ]
    },
    {
     "title": "Fan Speed %",
     "type": "graph",
     "description": "The fan speed value is the percent of the product's maximum noise tolerance fan speed that the device's fan is currently intended to run at. This value may exceed 100% in certain cases. Note: The reported speed is the intended fan speed. If the fan is physically blocked and unable to spin, this output will not match the actual fan speed. Many parts do not report fan speeds because they rely on cooling via fans in the surrounding enclosure.\n",
     "gridPos": { "h": 5, "w": 6, "x": 18, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "nvidia_smi_fan_speed_ratio{job=\"$job\", uuid=\"$gpu\"}",
       "legendFormat": "{{uuid}}"
      }
     ]
    },
    {
     "title": "Graphics Clock Speed",
     "type": "graph",
     "description": "Current frequency of graphics (shader) clock.",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 73 },
     "fieldConfig": { "defaults": { "unit": "hertz" } },
     "yaxes": [
      { "format": "hertz" }
     ],
     "targets": [
      {
       "expr": "nvidia_smi_clocks_current_graphics_clock_hz{job=\"$job\", uuid=\"$gpu\"}",
       "legendFormat": "{{uuid}}"
      }
     ]
    },
    {
     "title": "Video Clock Speed",
     "type": "graph",
     "description": "Current frequency of video encoder/decoder clock.",
     "gridPos": { "h": 5, "w": 6, "x": 6, "y": 73 },
     "fieldConfig": { "defaults": { "unit": "hertz" } },
     "yaxes": [
      { "format": "hertz" }
     ],
     "targets": [
      {
       "expr": "nvidia_smi_clocks_current_video_clock_hz{job=\"$job\", uuid=\"$gpu\"}",
       "legendFormat": "{{uuid}}"
      }
     ]
    },
    {
     "title": "SM Clock Speed",
     "type": "graph",
     "description": "Current frequency of SM (Streaming Multiprocessor) clock.",
     "gridPos": { "h": 5, "w": 6, "x": 12, "y": 73 },
     "fieldConfig": { "defaults": { "unit": "hertz" } },
     "yaxes": [
      { "format": "hertz" }
     ],
     "targets": [
      {
       "expr": "nvidia_smi_clocks_current_sm_clock_hz{job=\"$job\", uuid=\"$gpu\"}",
       "legendFormat": "{{uuid}}"
      }
     ]
    },
    {
     "title": "Memory Clock Speed",
     "type": "graph",
     "description": "Current frequency of memory clock.",
     "gridPos": { "h": 5, "w": 6, "x": 18, "y": 73 },
     "fieldConfig": { "defaults": { "unit": "hertz" } },
     "yaxes": [
      { "format": "hertz" }
     ],
     "targets": [
      {
       "expr": "nvidia_smi_clocks_current_memory_clock_hz{job=\"$job\", uuid=\"$gpu\"}",
       "legendFormat": "{{uuid}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Container Monitoring",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Running containers",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
       ],
       "expr": "count(container_last_seen{job=\"$job\",image=~\"(.)+\"})",
       "metrics": [
        { "field": "select field", "id": "1", "type": "count" }
       ],
       "query": "count(container_last_seen{instance=~\"$node\",job=~\"$job\",image!=\"\"})",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "graph",
     "gridPos": { "h": 5, "w": 21, "x": 3, "y": 59 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{job=\"$job\", name=~\"$container\",name=~\".+\"}[5m])) by (name) *100",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(container_memory_rss{job=\"$job\",name=~\"$container\",name=~\".+\"}) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Memory Cached",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(container_memory_cache{job=\"$job\",name=~\"$container\",name=~\".+\"}) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Received Network Traffic",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(container_network_receive_bytes_total{job=\"$job\",name=~\"$container\",name=~\".+\"}[5m])) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Sent Network Traffic",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 72 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(container_network_transmit_bytes_total{job=\"$job\",name=~\"$container\",name=~\".+\"}[5m])) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Visionaire4",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Event Dump Rate per Second",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(event_dump_counter{job=\"$job\"}[30s]))by(stream_id)",
       "legendFormat": "Stream ID={{stream_id}}"
      }
     ]
    },
    {
     "title": "Event Dump Rate per Second(by Analytic)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(event_dump_counter{job=\"$job\"}[30s]))by(analytic_id)",
       "legendFormat": "Analytic ID={{analytic_id}}"
      }
     ]
    },
    {
     "title": "Average Service Invoke Latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "avg(pipeline_invoke_latency{quantile=\"0.500000\", job=\"$job\"})by(service_class_name)",
       "legendFormat": "AVG(0.5) - {{service_class_name}}"
      }
     ]
    },
    {
     "title": "Upper Service Invoke Latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 12 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "max(pipeline_invoke_latency{quantile=\"0.900000\",job=\"$job\"})by(service_class_name)",
       "legendFormat": "Upper(0.9) - {{service_class_name}}"
      }
     ]
    },
    {
     "title": "Uncertainty Score ($err_range)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg_over_time(uncertainty_gauge{job=\"$job\"}[$err_range])",
       "legendFormat": "{{stream_id}} - {{analytic_id}}"
      }
     ]
    },
    {
     "title": "Error Rate ($err_range)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(\n(\ncount_over_time((uncertainty_gauge{job=\"$job\"} > 0.6)[$err_range:100ms])\nOR \n(count_over_time(uncertainty_gauge{job=\"$job\"}[$err_range:100ms]) - count_over_time(uncertainty_gauge{job=\"$job\"}[$err_range:100ms]))\n)\n/\ncount_over_time(uncertainty_gauge{job=\"$job\"}[$err_range:100ms])\n)",
       "legendFormat": "{{stream_id}} - {{analytic_id}}"
      }
     ]
    },
    {
     "title": "Pipeline Load Average",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg(pipeline_thread_load{quantile=\"0.500000\",job=\"$job\"})by(analytic_id)",
       "legendFormat": "AVG(0.5) {{analytic_id}}"
      }
     ]
    },
    {
     "title": "Pipeline Load Upper Percentile(0.9)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "max(pipeline_thread_load{quantile=\"0.900000\",job=\"$job\"})by(analytic_id)",
       "legendFormat": "Upper(0.9) {{analytic_id}}"
      }
     ]
    },
    {
     "title": "Pipeline Latency Average",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "avg(pipeline_latency{quantile=\"0.500000\",job=\"$job\"})by(analytic_id)",
       "legendFormat": "AVG(0.5) - {{analytic_id}}"
      }
     ]
    },
    {
     "title": "Pipeline Latency Upper Percentile(0.9)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 20 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "max(pipeline_latency{quantile=\"0.900000\",job=\"$job\"})by(analytic_id)",
       "legendFormat": "Upper(0.9) - {{analytic_id}}"
      }
     ]
    },
    {
     "title": "Stream FPS Status",
     "type": "graph",
     "gridPos": { "h": 8, "w": 5, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "stream_fps{job=\"$job\"}",
       "legendFormat": "Stream Id: {{stream_id}}"
      }
     ]
    },
    {
     "title": "Event Dump Latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 7, "x": 5, "y": 27 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "event_dump_average_latency{quantile=\"0.500000\", job=\"$job\"}",
       "legendFormat": "AVG(0.5)"
      },
      {
       "expr": "event_dump_average_latency{quantile=\"0.900000\", job=\"$job\"}",
       "legendFormat": "Upper(0.9)"
      },
      {
       "expr": "event_dump_average_latency{quantile=\"0.990000\", job=\"$job\"}",
       "legendFormat": "Corner(0.99)"
      }
     ]
    },
    {
     "title": "Stream Load Average",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "stream_thread_load{quantile=\"0.500000\",job=\"$job\"}",
       "legendFormat": "AVG(0.5) {{stream_id}}"
      }
     ]
    },
    {
     "title": "Stream Load Upper Percentile(0.9)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "stream_thread_load{quantile=\"0.900000\", job=\"$job\"}",
       "legendFormat": "Upper(0.9) {{stream_id}}"
      }
     ]
    },
    {
     "title": "MJPEG Connection Number",
     "type": "graph",
     "gridPos": { "h": 8, "w": 7, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg(mjpeg_connection_number{job=\"$job\"})by(stream_id)",
       "legendFormat": "Stream ID - {{stream_id}}"
      }
     ]
    },
    {
     "title": "MJPEG AVG Encode Latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 7, "y": 35 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "avg(mjpeg_encode_latency{quantile=\"0.500000\", job=\"$job\"}) by (stream_id)",
       "legendFormat": "Stream ID - {{stream_id}}"
      }
     ]
    },
    {
     "title": "MJPEG Upper Encode Latency(0.9)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 9, "x": 15, "y": 35 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "max(mjpeg_encode_latency{quantile=\"0.900000\",job=\"$job\"}) by (stream_id)",
       "legendFormat": "Stream ID - {{stream_id}}"
      }
     ]
    },
    {
     "title": "Average MJPEG Decode Frame per Second",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg(rate(mjpeg_frame_counter{job=\"$job\"}[1m])/mjpeg_connection_number{job=\"$job\"})by(stream_id)",
       "legendFormat": "Stream Id - {{stream_id}}"
      }
     ]
    },
    {
     "title": "Total MJPEG Decoder Throughput",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "expr": "avg(rate(mjpeg_frame_size_counter{job=\"$job\"}[1m]))by(stream_id)*8",
       "legendFormat": "Stream Id - {{stream_id}}"
      }
     ]
    },
    {
     "title": "Object Number Tracker",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(pipeline_object_number{job=\"$job\"})by(analytic_id)",
       "legendFormat": "Pipeline Objects - {{analytic_id}}"
      },
      {
       "expr": "sum(stream_object_number{job=\"$job\"})by(node_num)",
       "legendFormat": "Stream Objects"
      },
      {
       "expr": "sum(service_object_number{job=\"$job\"})by(service_class_name)",
       "legendFormat": "Service Objects - {{service_class_name}}"
      }
     ]
    },
    {
     "title": "Thread Restart per Second",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(pipeline_restarted_counter{job=\"$job\"}[15m]))by(analytic_id)",
       "legendFormat": "Pipeline Threads - {{analytic_id}}"
      },
      {
       "expr": "sum(rate(stream_restarted_counter{job=\"$job\"}[15m]))",
       "legendFormat": "Stream Threads"
      },
      {
       "expr": "sum(rate(service_restarted_counter{job=\"$job\"}[15m]))by(service_class_name)",
       "legendFormat": "Service Threads - {{service_class_name}}"
      }
     ]
    },
    {
     "title": "Thread Number Tracker",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 59 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(pipeline_thread_number{job=\"$job\"})by(analytic_id)",
       "legendFormat": "Pipeline Threads - {{analytic_id}}"
      },
      {
       "expr": "sum(stream_thread_number{job=\"$job\"})",
       "legendFormat": "Stream Threads"
      },
      {
       "expr": "sum(service_thread_number{job=\"$job\"})by(service_class_name)",
       "legendFormat": "Service Threads - {{service_class_name}}"
      }
     ]
    }
   ]
  },
  { "title": "Fremis-N", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Latency Face Recognition",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "latency_face_recognition{job=\"$job\"}",
     "legendFormat": "{{quantile}}"
    },
    {
     "expr": "avg(latency_face_extraction{job=\"$job\"})"
    },
    {
     "expr": "avg(latency_face_id_search{job=\"$job\"})+avg(latency_face_extraction{job=\"$job\"})"
    }
   ]
  },
  {
   "title": "Latency Face Extraction",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 5 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "latency_face_extraction{job=\"$job\"}",
     "legendFormat": "{{quantile}}"
    },
    {
     "expr": "avg(latency_face_extraction{job=\"$job\"})"
    },
    {
     "expr": "min(latency_face_extraction{job=\"$job\"})"
    }
   ]
  },
  {
   "title": "Latency Face ID search",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 16, "y": 5 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "latency_face_id_search{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Latency Face Detection",
   "type": "graph",
   "description": "Including:\n- Face Detection Inference\n- Sort faces from the largest",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "latency_face_detection{job=\"$job\"}",
     "legendFormat": "{{quantile}}"
    },
    {
     "expr": "avg(latency_face_detection{job=\"$job\"})"
    },
    {
     "expr": "min(latency_face_detection{job=\"$job\"})"
    }
   ]
  },
  {
   "title": "Latency Create Enrollment",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 13 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "latency_create_enrollment{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Face Queue",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 16, "y": 13 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "queue_face{job=\"$job\"}"
    }
   ]
  }
 ]
}